// Config schema for dsh-web-notifications.
//
// The settings loader validates non-strictly: unknown keys survive silently,
// so `reportUnknownKeys` surfaces them in the host log instead. Every field
// except `version` and `dataRoot` is volatile, which means edits made in the
// Settings UI are applied to the live config object in place (read them with
// `.get()`) without restarting the plugin fiber.

import z from '@deepseek-ai/schemastery'
import { dshHomePath } from '@deepseek-ai/dsh-home-paths'

/** Config document revision; bump when the shape changes and add a migration. */
export const CONFIG_VERSION = 1

/**
 * Preset tone ids mapped to the file served for each. Seven are generated by
 * tools/generate-tones.mjs and shipped as WAV; four come from the OpenGameArt
 * pack described in tones/CREDITS.md and are kept as their author encoded them,
 * as OGG. The browser half mirrors this table by hand, like the defaults below.
 */
export const PRESET_TONE_FILES = Object.freeze({
  chime: 'chime.wav',
  ping: 'ping.wav',
  bubble: 'bubble.wav',
  marimba: 'marimba.wav',
  knock: 'knock.wav',
  alarm: 'alarm.wav',
  'triple-tick': 'triple-tick.wav',
  ding: 'ding.ogg',
  chimes: 'chimes.ogg',
  'ding-deep': 'ding-deep.ogg',
  dum: 'dum.ogg',
})

/** Preset tone ids. */
export const PRESET_TONES = Object.freeze(Object.keys(PRESET_TONE_FILES))

/**
 * Per-type defaults, the single source for the schema below, the host test
 * bodies, and the trigger tests. The browser half mirrors this table by hand
 * (it imports nothing), so a new type is added in both places.
 */
export const TYPE_DEFAULTS = Object.freeze({
  turnComplete: { enabled: true, tone: 'ding' },
  approvalRequired: { enabled: true, tone: 'bubble' },
  agentStalled: { enabled: true, tone: 'dum' },
  // `turnFailed` deliberately starts on the same tone as `agentStalled`, and
  // `goalComplete` on the same tone as `turnComplete`; the Settings panel says
  // so, and each type can be given its own tone there.
  turnFailed: { enabled: true, tone: 'dum' },
  inputRequired: { enabled: true, tone: 'knock' },
  goalComplete: { enabled: true, tone: 'ding' },
  // Off by default: goals only exist in sessions that created one, so most
  // users would never see this fire.
  goalBlocked: { enabled: false, tone: 'triple-tick' },
})

/** Notification type ids shared with the browser half. */
export const NOTIFICATION_TYPES = Object.freeze(Object.keys(TYPE_DEFAULTS))

const toneRecordShape = {
  id: z.string().min(1),
  name: z.string().min(1),
  file: z.string().min(1),
  bytes: z.number().step(1).min(0),
}

/**
 * Keep only well-formed tone records out of a stored `customTones` array.
 *
 * The loader checks array elements loosely and accepts a `null` row, and both
 * halves read `tone.id` on every entry, so one malformed row in a stored
 * document would otherwise take the whole Settings panel down.
 *
 * @param list - raw `customTones` value, possibly undefined or malformed.
 * @returns the entries that carry a usable id and file name.
 */
export function usableTones(list) {
  if (!Array.isArray(list)) return []
  return list.filter(
    (tone) =>
      tone !== null &&
      typeof tone === 'object' &&
      typeof tone.id === 'string' &&
      tone.id !== '' &&
      typeof tone.file === 'string' &&
      tone.file !== '',
  )
}

/**
 * Read the tone record out of an `uploadTone` reply.
 *
 * The Host answers flat (`{ ok, id, name, file, bytes }`). The nested shape
 * under `tone` is still accepted because that is what earlier builds sent,
 * and a reply that carries neither is reported as absent rather than passed
 * through: an `undefined` record appended to the manifest is what the profile
 * document then stored as a `- null` row.
 *
 * @param reply - raw `uploadTone` reply.
 * @returns the normalized record, or null when the reply carries none.
 */
export function toneRecordFrom(reply) {
  const source = reply !== null && typeof reply === 'object' ? (reply.tone ?? reply) : null
  if (source === null || typeof source !== 'object') return null
  const { id, name, file, bytes } = source
  if (typeof id !== 'string' || id === '' || typeof file !== 'string' || file === '') return null
  return {
    id,
    name: typeof name === 'string' && name !== '' ? name : id,
    file,
    bytes: typeof bytes === 'number' && Number.isFinite(bytes) ? bytes : 0,
  }
}

/**
 * Unwrap one gateway unary reply.
 *
 * Every Remote call resolves to an envelope: `{ ok: true, value }` when the
 * call went through, `{ ok: false, error }` when it did not. A controller's
 * own `{ ok, error }` answer therefore sits one level deeper, under `value`.
 * Reading the envelope as if it were the answer is what made a tone upload
 * look successful while carrying no tone record at all.
 *
 * @param reply - raw envelope from the gateway client.
 * @returns the controller's reply, or a business error when the call failed.
 */
export function remoteReplyPayload(reply) {
  if (reply === null || typeof reply !== 'object') return reply
  if (reply.ok === false) {
    const error = reply.error
    const message = error !== null && typeof error === 'object' ? (error.message ?? error.code) : error
    return { ok: false, error: String(message ?? 'the remote call failed') }
  }
  return Object.hasOwn(reply, 'value') ? reply.value : reply
}

const typeShape = (defaults) => ({
  enabled: z.boolean().default(defaults.enabled).volatile(),
  tone: z.string().default(defaults.tone).volatile(),
})

// Plain shape objects (not schemas) so `reportUnknownKeys` can walk the same
// key tree the schema is built from. Adding a type here is additive: a stored
// document without the new `types.<id>` subtree is filled from `TYPE_DEFAULTS`
// by the loader, so `CONFIG_VERSION` does not move.
//
// The per-type `cooldownSeconds` and `toneEveryStall` keys were removed: every
// event now emits its card and tone. A document still carrying them keeps
// working: the loader is non-strict, and each leftover key is reported once as
// an unknown key rather than breaking the load. `CONFIG_VERSION` stays at 1
// because the host half never writes config (the browser owns every write), so
// there is no in-place migration to run; the stale lines are deleted by hand or
// by a fresh Settings write.
const typeShapes = Object.fromEntries(
  Object.entries(TYPE_DEFAULTS).map(([name, defaults]) => [name, typeShape(defaults)]),
)

const globalShape = {
  version: z.number().step(1).default(CONFIG_VERSION),
  // Plugin-owned data directory; nothing is ever written outside it.
  dataRoot: z.string().default(dshHomePath('notifications')),
  enabled: z.boolean().default(true).volatile(),
  volume: z.number().step(1).min(0).max(100).default(100).volatile(),
  muteWhenFocused: z.boolean().default(false).volatile(),
  onlyWhenHidden: z.boolean().default(true).volatile(),
  maxBodyChars: z.number().step(1).min(20).max(250).default(200).volatile(),
  subagentNotifications: z.boolean().default(false).volatile(),
  toneMaxBytes: z.number().step(1).min(1024).max(8388608).default(512000).volatile(),
  toneMaxCount: z.number().step(1).min(1).max(500).default(50).volatile(),
  customTones: z.array(z.object(toneRecordShape)).default([]).volatile(),
  types: z.object(Object.fromEntries(Object.entries(typeShapes).map(([name, shape]) => [name, z.object(shape)]))),
}

export const Config = z.object(globalShape)

/**
 * `version` fences future shape changes. v1 is the first revision, so there is
 * nothing to migrate yet. When the shape changes, add a rewrite step here that
 * persists through the settings service and bump CONFIG_VERSION; a document
 * newer than this plugin is reported rather than silently truncated.
 *
 * @param logger - host logger scoped to this plugin.
 * @param config - validated (non-strict) config section.
 */
export function migrateConfig(logger, config) {
  if (typeof config.version === 'number' && config.version > CONFIG_VERSION) {
    logger.warn(
      `notifications: config version ${config.version} is newer than plugin v${CONFIG_VERSION}; ` +
        'unknown keys will be reported, not migrated',
    )
  }
}

/**
 * Report config keys the schema does not declare. The loader keeps unknown
 * keys, so a typo in the profile patch would otherwise be invisible.
 *
 * @param logger - host logger scoped to this plugin.
 * @param config - validated (non-strict) config section.
 */
export function reportUnknownKeys(logger, config) {
  reportKeys(logger, '', config, globalShape)
  reportKeys(logger, 'types.', config.types, typeShapes)
  for (const typeName of Object.keys(typeShapes)) {
    reportKeys(logger, `types.${typeName}.`, config.types?.[typeName], typeShapes[typeName])
  }
  const customTones = config.customTones?.get?.() ?? []
  for (const [index, tone] of customTones.entries()) {
    reportKeys(logger, `customTones[${index}].`, tone, toneRecordShape)
  }
}

/**
 * Log one warning per key present in `value` but absent from `shape`.
 *
 * @param logger - host logger scoped to this plugin.
 * @param prefix - dotted path prefix for the reported key.
 * @param value - config subtree (may be undefined).
 * @param shape - declared shape for that subtree.
 */
function reportKeys(logger, prefix, value, shape) {
  if (value === null || typeof value !== 'object' || Array.isArray(value)) return
  for (const key of Object.keys(value)) {
    if (!(key in shape)) logger.warn(`notifications: unknown config key "${prefix}${key}" ignored`)
  }
}
